name: Spellcheck

# **What it does**: Spell-checks all the markdown files underneath the "content" folder
# **Why we have it**: To prevent spelling errors and typos in documentation
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  push:
    branches:
      - main
    paths:
      - 'content/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'content/**/*'
jobs:
  spellcheck:
    name: 'Spellcheck Docs Content'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install cSpell
        run: npm install -g cspell
      - name: Run cSpell
        run: cspell --config ./cSpell.json "content/**/*.md" --no-progress
