name: Spellcheck

# **What it does**: Spell-checks all the markdown files underneath the "content" folder
# **Why we have it**: To prevent spelling errors and typos in documentation
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  push:
    branches:
      - main
    paths:
      - 'content/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'content/**/*'
jobs:
  spellcheck:
    name: 'Spellcheck Docs Content'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
      - name: Install cSpell
        run: npm install -g cspell
      - name: Run cSpell
        run: cspell --config ./cSpell.json "content/**/*.md" --no-progress
